auto_scale_lr = dict(base_batch_size=16, enable=True)
backend_args = None
data_root = '/root/autodl-tmp/dataset/coco/crop_child/'
dataset_type = 'CocoDataset'
default_hooks = dict(
    checkpoint=dict(
        interval=10,
        rule=[
            'greater',
            'greater',
        ],
        save_best=[
            'coco/bbox_mAP_50',
            'coco/bbox_mAP',
        ],
        type='CheckpointHook'),
    logger=dict(interval=50, type='LoggerHook'),
    param_scheduler=dict(type='ParamSchedulerHook'),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    timer=dict(type='IterTimerHook'),
    visualization=dict(
        draw=False,
        test_out_dir='teeth_results_ap',
        type='DetVisualizationHook'))
default_scope = 'mmdet'
env_cfg = dict(
    cudnn_benchmark=False,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
launcher = 'none'
load_from = 'work_dirs/faster-rcnn_r50_fpn_1x_coco_teeth/best_coco_bbox_mAP_epoch_53.pth'
log_level = 'INFO'
log_processor = dict(by_epoch=True, type='LogProcessor', window_size=50)
metainfo = dict(
    classes=(
        '11',
        '12',
        '13',
        '14',
        '15',
        '16',
        '17',
        '21',
        '22',
        '23',
        '24',
        '25',
        '26',
        '27',
        '31',
        '32',
        '33',
        '34',
        '35',
        '36',
        '37',
        '41',
        '42',
        '43',
        '44',
        '45',
        '46',
        '47',
        '51',
        '52',
        '53',
        '54',
        '55',
        '61',
        '62',
        '63',
        '64',
        '65',
        '71',
        '72',
        '73',
        '74',
        '75',
        '81',
        '82',
        '83',
        '84',
        '85',
    ),
    palette=[
        (
            230,
            50,
            80,
        ),
        (
            60,
            180,
            75,
        ),
        (
            0,
            130,
            200,
        ),
        (
            245,
            150,
            0,
        ),
        (
            145,
            30,
            180,
        ),
        (
            70,
            240,
            120,
        ),
        (
            220,
            190,
            40,
        ),
        (
            170,
            110,
            80,
        ),
        (
            30,
            200,
            220,
        ),
        (
            255,
            0,
            100,
        ),
        (
            40,
            90,
            160,
        ),
        (
            210,
            80,
            150,
        ),
        (
            100,
            200,
            0,
        ),
        (
            180,
            0,
            90,
        ),
        (
            50,
            160,
            200,
        ),
        (
            255,
            120,
            60,
        ),
        (
            10,
            140,
            70,
        ),
        (
            200,
            50,
            120,
        ),
        (
            80,
            180,
            220,
        ),
        (
            240,
            60,
            180,
        ),
        (
            120,
            200,
            50,
        ),
        (
            160,
            30,
            150,
        ),
        (
            20,
            220,
            160,
        ),
        (
            255,
            90,
            30,
        ),
        (
            70,
            130,
            210,
        ),
        (
            0,
            180,
            240,
        ),
        (
            220,
            140,
            100,
        ),
        (
            50,
            70,
            190,
        ),
        (
            180,
            200,
            40,
        ),
        (
            130,
            0,
            120,
        ),
        (
            200,
            180,
            0,
        ),
        (
            90,
            50,
            140,
        ),
        (
            30,
            240,
            100,
        ),
        (
            255,
            70,
            150,
        ),
        (
            110,
            160,
            60,
        ),
        (
            0,
            100,
            220,
        ),
        (
            240,
            200,
            80,
        ),
        (
            150,
            80,
            170,
        ),
        (
            70,
            0,
            160,
        ),
        (
            255,
            160,
            20,
        ),
        (
            40,
            200,
            140,
        ),
        (
            190,
            60,
            110,
        ),
        (
            80,
            220,
            180,
        ),
        (
            230,
            0,
            70,
        ),
        (
            120,
            120,
            200,
        ),
        (
            60,
            150,
            30,
        ),
        (
            210,
            100,
            180,
        ),
        (
            10,
            80,
            130,
        ),
    ])
model = dict(
    backbone=dict(
        depth=50,
        frozen_stages=1,
        init_cfg=dict(checkpoint='torchvision://resnet50', type='Pretrained'),
        norm_cfg=dict(requires_grad=True, type='BN'),
        norm_eval=True,
        num_stages=4,
        out_indices=(
            0,
            1,
            2,
            3,
        ),
        style='pytorch',
        type='ResNet'),
    data_preprocessor=dict(
        bgr_to_rgb=True,
        mean=[
            123.675,
            116.28,
            103.53,
        ],
        pad_size_divisor=32,
        std=[
            58.395,
            57.12,
            57.375,
        ],
        type='DetDataPreprocessor'),
    neck=dict(
        in_channels=[
            256,
            512,
            1024,
            2048,
        ],
        num_outs=5,
        out_channels=256,
        type='FPN'),
    roi_head=dict(
        bbox_head=dict(
            bbox_coder=dict(
                target_means=[
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                ],
                target_stds=[
                    0.1,
                    0.1,
                    0.2,
                    0.2,
                ],
                type='DeltaXYWHBBoxCoder'),
            fc_out_channels=1024,
            in_channels=256,
            loss_bbox=dict(loss_weight=1.0, type='L1Loss'),
            loss_cls=dict(
                loss_weight=1.0, type='CrossEntropyLoss', use_sigmoid=False),
            num_classes=48,
            reg_class_agnostic=False,
            roi_feat_size=7,
            type='ConvFCBBoxHeadAddVisualFeature'),
        bbox_roi_extractor=dict(
            featmap_strides=[
                4,
                8,
                16,
                32,
            ],
            out_channels=256,
            roi_layer=dict(output_size=7, sampling_ratio=0, type='RoIAlign'),
            type='SingleRoIExtractor'),
        type='GenerateGNNDatasetStandardRoIHead'),
    rpn_head=dict(
        anchor_generator=dict(
            ratios=[
                0.5,
                0.75,
                1.5,
            ],
            scales=[
                8,
            ],
            strides=[
                4,
                8,
                16,
                32,
                64,
            ],
            type='AnchorGenerator'),
        bbox_coder=dict(
            target_means=[
                0.0,
                0.0,
                0.0,
                0.0,
            ],
            target_stds=[
                1.0,
                1.0,
                1.0,
                1.0,
            ],
            type='DeltaXYWHBBoxCoder'),
        feat_channels=256,
        in_channels=256,
        loss_bbox=dict(loss_weight=1.0, type='L1Loss'),
        loss_cls=dict(
            loss_weight=1.0, type='CrossEntropyLoss', use_sigmoid=True),
        type='RPNHead'),
    test_cfg=dict(
        rcnn=dict(
            max_per_img=100,
            nms=dict(iou_threshold=0.5, type='nms'),
            score_thr=0.05),
        rpn=dict(
            max_per_img=1000,
            min_bbox_size=0,
            nms=dict(iou_threshold=0.7, type='nms'),
            nms_pre=1000)),
    train_cfg=dict(
        rcnn=dict(
            assigner=dict(
                ignore_iof_thr=-1,
                match_low_quality=False,
                min_pos_iou=0.5,
                neg_iou_thr=0.5,
                pos_iou_thr=0.5,
                type='MaxIoUAssigner'),
            debug=False,
            pos_weight=-1,
            sampler=dict(
                add_gt_as_proposals=True,
                neg_pos_ub=-1,
                num=512,
                pos_fraction=0.25,
                type='RandomSampler')),
        rpn=dict(
            allowed_border=-1,
            assigner=dict(
                ignore_iof_thr=-1,
                match_low_quality=True,
                min_pos_iou=0.3,
                neg_iou_thr=0.3,
                pos_iou_thr=0.7,
                type='MaxIoUAssigner'),
            debug=False,
            pos_weight=-1,
            sampler=dict(
                add_gt_as_proposals=False,
                neg_pos_ub=-1,
                num=256,
                pos_fraction=0.5,
                type='RandomSampler')),
        rpn_proposal=dict(
            max_per_img=1000,
            min_bbox_size=0,
            nms=dict(iou_threshold=0.7, type='nms'),
            nms_pre=2000)),
    type='FasterRCNN')
optim_wrapper = dict(
    clip_grad=dict(max_norm=35, norm_type=2),
    optimizer=dict(lr=0.002, momentum=0.9, type='SGD', weight_decay=0.0001),
    type='OptimWrapper')
param_scheduler = [
    dict(
        begin=0, by_epoch=False, end=1500, start_factor=0.001,
        type='LinearLR'),
    dict(
        begin=0,
        by_epoch=True,
        end=150,
        gamma=0.1,
        milestones=[
            100,
            140,
        ],
        type='MultiStepLR'),
]
resume = False
test_cfg = dict(type='TestLoop')
test_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='annotations/val.json',
        backend_args=None,
        data_prefix=dict(img='preprocessing_images/'),
        data_root='C:\\Users\\Administrator\\PycharmProjects\\mmdetection-dental\\dataset\\coco\\crop_child\\',
        metainfo=dict(
            classes=(
                '11',
                '12',
                '13',
                '14',
                '15',
                '16',
                '17',
                '21',
                '22',
                '23',
                '24',
                '25',
                '26',
                '27',
                '31',
                '32',
                '33',
                '34',
                '35',
                '36',
                '37',
                '41',
                '42',
                '43',
                '44',
                '45',
                '46',
                '47',
                '51',
                '52',
                '53',
                '54',
                '55',
                '61',
                '62',
                '63',
                '64',
                '65',
                '71',
                '72',
                '73',
                '74',
                '75',
                '81',
                '82',
                '83',
                '84',
                '85',
            ),
            palette=[
                (
                    230,
                    50,
                    80,
                ),
                (
                    60,
                    180,
                    75,
                ),
                (
                    0,
                    130,
                    200,
                ),
                (
                    245,
                    150,
                    0,
                ),
                (
                    145,
                    30,
                    180,
                ),
                (
                    70,
                    240,
                    120,
                ),
                (
                    220,
                    190,
                    40,
                ),
                (
                    170,
                    110,
                    80,
                ),
                (
                    30,
                    200,
                    220,
                ),
                (
                    255,
                    0,
                    100,
                ),
                (
                    40,
                    90,
                    160,
                ),
                (
                    210,
                    80,
                    150,
                ),
                (
                    100,
                    200,
                    0,
                ),
                (
                    180,
                    0,
                    90,
                ),
                (
                    50,
                    160,
                    200,
                ),
                (
                    255,
                    120,
                    60,
                ),
                (
                    10,
                    140,
                    70,
                ),
                (
                    200,
                    50,
                    120,
                ),
                (
                    80,
                    180,
                    220,
                ),
                (
                    240,
                    60,
                    180,
                ),
                (
                    120,
                    200,
                    50,
                ),
                (
                    160,
                    30,
                    150,
                ),
                (
                    20,
                    220,
                    160,
                ),
                (
                    255,
                    90,
                    30,
                ),
                (
                    70,
                    130,
                    210,
                ),
                (
                    0,
                    180,
                    240,
                ),
                (
                    220,
                    140,
                    100,
                ),
                (
                    50,
                    70,
                    190,
                ),
                (
                    180,
                    200,
                    40,
                ),
                (
                    130,
                    0,
                    120,
                ),
                (
                    200,
                    180,
                    0,
                ),
                (
                    90,
                    50,
                    140,
                ),
                (
                    30,
                    240,
                    100,
                ),
                (
                    255,
                    70,
                    150,
                ),
                (
                    110,
                    160,
                    60,
                ),
                (
                    0,
                    100,
                    220,
                ),
                (
                    240,
                    200,
                    80,
                ),
                (
                    150,
                    80,
                    170,
                ),
                (
                    70,
                    0,
                    160,
                ),
                (
                    255,
                    160,
                    20,
                ),
                (
                    40,
                    200,
                    140,
                ),
                (
                    190,
                    60,
                    110,
                ),
                (
                    80,
                    220,
                    180,
                ),
                (
                    230,
                    0,
                    70,
                ),
                (
                    120,
                    120,
                    200,
                ),
                (
                    60,
                    150,
                    30,
                ),
                (
                    210,
                    100,
                    180,
                ),
                (
                    10,
                    80,
                    130,
                ),
            ]),
        pipeline=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(keep_ratio=True, scale=(
                1333,
                800,
            ), type='Resize'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(
                brightness_delta=32,
                contrast_range=(
                    0.5,
                    1.5,
                ),
                hue_delta=0,
                saturation_range=(
                    0.3,
                    1.7,
                ),
                type='PhotoMetricDistortion'),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                ),
                type='PackDetInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    drop_last=False,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
    ann_file='C:\\Users\\Administrator\\PycharmProjects\\mmdetection-dental\\dataset\\coco\\crop_child\\annotations\\val.json',
    backend_args=None,
    classwise=True,
    format_only=False,
    metric=[
        'bbox',
    ],
    type='GenerateGNNData')
test_pipeline = [
    dict(backend_args=None, type='LoadImageFromFile'),
    dict(keep_ratio=True, scale=(
        1333,
        800,
    ), type='Resize'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        brightness_delta=32,
        contrast_range=(
            0.5,
            1.5,
        ),
        hue_delta=0,
        saturation_range=(
            0.3,
            1.7,
        ),
        type='PhotoMetricDistortion'),
    dict(
        meta_keys=(
            'img_id',
            'img_path',
            'ori_shape',
            'img_shape',
            'scale_factor',
        ),
        type='PackDetInputs'),
]
train_cfg = dict(max_epochs=100, type='EpochBasedTrainLoop', val_interval=1)
train_dataloader = dict(
    batch_sampler=dict(type='AspectRatioBatchSampler'),
    batch_size=8,
    dataset=dict(
        ann_file='annotations/train.json',
        backend_args=None,
        data_prefix=dict(img='preprocessing_images/'),
        data_root='/root/autodl-tmp/dataset/coco/crop_child/',
        filter_cfg=dict(filter_empty_gt=True, min_size=32),
        metainfo=dict(
            classes=(
                '11',
                '12',
                '13',
                '14',
                '15',
                '16',
                '17',
                '21',
                '22',
                '23',
                '24',
                '25',
                '26',
                '27',
                '31',
                '32',
                '33',
                '34',
                '35',
                '36',
                '37',
                '41',
                '42',
                '43',
                '44',
                '45',
                '46',
                '47',
                '51',
                '52',
                '53',
                '54',
                '55',
                '61',
                '62',
                '63',
                '64',
                '65',
                '71',
                '72',
                '73',
                '74',
                '75',
                '81',
                '82',
                '83',
                '84',
                '85',
            ),
            palette=[
                (
                    230,
                    50,
                    80,
                ),
                (
                    60,
                    180,
                    75,
                ),
                (
                    0,
                    130,
                    200,
                ),
                (
                    245,
                    150,
                    0,
                ),
                (
                    145,
                    30,
                    180,
                ),
                (
                    70,
                    240,
                    120,
                ),
                (
                    220,
                    190,
                    40,
                ),
                (
                    170,
                    110,
                    80,
                ),
                (
                    30,
                    200,
                    220,
                ),
                (
                    255,
                    0,
                    100,
                ),
                (
                    40,
                    90,
                    160,
                ),
                (
                    210,
                    80,
                    150,
                ),
                (
                    100,
                    200,
                    0,
                ),
                (
                    180,
                    0,
                    90,
                ),
                (
                    50,
                    160,
                    200,
                ),
                (
                    255,
                    120,
                    60,
                ),
                (
                    10,
                    140,
                    70,
                ),
                (
                    200,
                    50,
                    120,
                ),
                (
                    80,
                    180,
                    220, 
                ),
                (
                    240,
                    60,
                    180,
                ),
                (
                    120,
                    200,
                    50,
                ),
                (
                    160,
                    30,
                    150,
                ),
                (
                    20,
                    220,
                    160,
                ),
                (
                    255,
                    90,
                    30,
                ),
                (
                    70,
                    130,
                    210,
                ),
                (
                    0,
                    180,
                    240,
                ),
                (
                    220,
                    140,
                    100,
                ),
                (
                    50,
                    70,
                    190,
                ),
                (
                    180,
                    200,
                    40,
                ),
                (
                    130,
                    0,
                    120,
                ),
                (
                    200,
                    180,
                    0,
                ),
                (
                    90,
                    50,
                    140,
                ),
                (
                    30,
                    240,
                    100,
                ),
                (
                    255,
                    70,
                    150,
                ),
                (
                    110,
                    160,
                    60,
                ),
                (
                    0,
                    100,
                    220,
                ),
                (
                    240,
                    200,
                    80,
                ),
                (
                    150,
                    80,
                    170,
                ),
                (
                    70,
                    0,
                    160,
                ),
                (
                    255,
                    160,
                    20,
                ),
                (
                    40,
                    200,
                    140,
                ),
                (
                    190,
                    60,
                    110,
                ),
                (
                    80,
                    220,
                    180,
                ),
                (
                    230,
                    0,
                    70,
                ),
                (
                    120,
                    120,
                    200,
                ),
                (
                    60,
                    150,
                    30,
                ),
                (
                    210,
                    100,
                    180,
                ),
                (
                    10,
                    80,
                    130,
                ),
            ]),
        pipeline=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(keep_ratio=True, scale=(
                1333,
                800,
            ), type='Resize'),
            dict(size_divisor=32, type='Pad'),
            dict(type='PackDetInputs'),
        ],
        type='CocoDataset'),
    num_workers=2,
    persistent_workers=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_pipeline = [
    dict(backend_args=None, type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(keep_ratio=True, scale=(
        1333,
        800,
    ), type='Resize'),
    dict(size_divisor=32, type='Pad'),
    dict(type='PackDetInputs'),
]
val_cfg = dict(type='ValLoop')
val_dataloader = dict(
    batch_size=8,
    dataset=dict(
        ann_file='annotations/val.json',
        backend_args=None,
        data_prefix=dict(img='preprocessing_images/'),
        data_root='/root/autodl-tmp/dataset/coco/crop_child/',
        metainfo=dict(
            classes=(
                '11',
                '12',
                '13',
                '14',
                '15',
                '16',
                '17',
                '21',
                '22',
                '23',
                '24',
                '25',
                '26',
                '27',
                '31',
                '32',
                '33',
                '34',
                '35',
                '36',
                '37',
                '41',
                '42',
                '43',
                '44',
                '45',
                '46',
                '47',
                '51',
                '52',
                '53',
                '54',
                '55',
                '61',
                '62',
                '63',
                '64',
                '65',
                '71',
                '72',
                '73',
                '74',
                '75',
                '81',
                '82',
                '83',
                '84',
                '85',
            ),
            palette=[
                (
                    230,
                    50,
                    80,
                ),
                (
                    60,
                    180,
                    75,
                ),
                (
                    0,
                    130,
                    200,
                ),
                (
                    245,
                    150,
                    0,
                ),
                (
                    145,
                    30,
                    180,
                ),
                (
                    70,
                    240,
                    120,
                ),
                (
                    220,
                    190,
                    40,
                ),
                (
                    170,
                    110,
                    80,
                ),
                (
                    30,
                    200,
                    220,
                ),
                (
                    255,
                    0,
                    100,
                ),
                (
                    40,
                    90,
                    160,
                ),
                (
                    210,
                    80,
                    150,
                ),
                (
                    100,
                    200,
                    0,
                ),
                (
                    180,
                    0,
                    90,
                ),
                (
                    50,
                    160,
                    200,
                ),
                (
                    255,
                    120,
                    60,
                ),
                (
                    10,
                    140,
                    70,
                ),
                (
                    200,
                    50,
                    120,
                ),
                (
                    80,
                    180,
                    220,
                ),
                (
                    240,
                    60,
                    180,
                ),
                (
                    120,
                    200,
                    50,
                ),
                (
                    160,
                    30,
                    150,
                ),
                (
                    20,
                    220,
                    160,
                ),
                (
                    255,
                    90,
                    30,
                ),
                (
                    70,
                    130,
                    210,
                ),
                (
                    0,
                    180,
                    240,
                ),
                (
                    220,
                    140,
                    100,
                ),
                (
                    50,
                    70,
                    190,
                ),
                (
                    180,
                    200,
                    40,
                ),
                (
                    130,
                    0,
                    120,
                ),
                (
                    200,
                    180,
                    0,
                ),
                (
                    90,
                    50,
                    140,
                ),
                (
                    30,
                    240,
                    100,
                ),
                (
                    255,
                    70,
                    150,
                ),
                (
                    110,
                    160,
                    60,
                ),
                (
                    0,
                    100,
                    220,
                ),
                (
                    240,
                    200,
                    80,
                ),
                (
                    150,
                    80,
                    170,
                ),
                (
                    70,
                    0,
                    160,
                ),
                (
                    255,
                    160,
                    20,
                ),
                (
                    40,
                    200,
                    140,
                ),
                (
                    190,
                    60,
                    110,
                ),
                (
                    80,
                    220,
                    180,
                ),
                (
                    230,
                    0,
                    70,
                ),
                (
                    120,
                    120,
                    200,
                ),
                (
                    60,
                    150,
                    30,
                ),
                (
                    210,
                    100,
                    180,
                ),
                (
                    10,
                    80,
                    130,
                ),
            ]),
        pipeline=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(keep_ratio=True, scale=(
                1333,
                800,
            ), type='Resize'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(
                brightness_delta=32,
                contrast_range=(
                    0.5,
                    1.5,
                ),
                hue_delta=0,
                saturation_range=(
                    0.3,
                    1.7,
                ),
                type='PhotoMetricDistortion'),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                ),
                type='PackDetInputs'),
        ],
        test_mode=True,
        type='CocoDataset'),
    drop_last=False,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
val_evaluator = dict(
    ann_file='C:\\Users\\Administrator\\PycharmProjects\\mmdetection-dental\\dataset\\coco\\crop_child\\annotations\\train.json',
    backend_args=None,
    classwise=True,
    format_only=False,
    metric=[
        'bbox',
    ],
    type='GenerateGNNData')
vis_backends = [
    dict(type='LocalVisBackend'),
]
visualizer = dict(
    name='visualizer',
    type='DetLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
    ])
work_dir = './work_dirs/faster-rcnn_r50_fpn_1x_coco_teeth'
